---
webservers:
  hosts:
    wp-node1:   
      ansible_host: 192.168.0.110
      hostname: wp-node1
    wp-node2:
      ansible_host: 192.168.0.111
      hostname: wp-node2
  vars:
    ansible_connection: ssh
    ansible_user: kate
    db_host: 192.168.0.109
    wordpress_version: 5.8.1
    wordpress_parent_path: /var/www/
    wordpress_path: "{{ wordpress_parent_path }}/wordpress"
    wordpress_owner: root
    wordpress_group: root
    db_name: leto
    db_user: leto
    db_pass: 1qaz@WSX
dbservers:
  hosts:
    dbserver:
      ansible_host: 192.168.0.109
      ansible_connection: ssh
      ansible_user: kate
      db_name: leto
      db_user: leto
      db_pass: 1qaz@WSX
      root_pass: 1qaz@WSX
haproxy:
  hosts:
    haproxy_1:
      ansible_host: 192.168.0.108
      ansible_connection: ssh
      ansible_user: kate
      
