---
webservers:
  hosts:
    192.168.1.110:
    192.168.1.111:
      vars:
        ansible_connection: ssh
        ansible_user: kate
dbservers:
  hosts:  
    192.168.1.109:
      vars:
        ansible_connection: ssh
        ansible_user: kate
        db_name: leto
        db_user: leto
        db_pass: 1qaz@WSX
        root_pass: 1qaz@WSX
haproxy:
  hosts:
    192.168.1.108:
      vars:
        ansible_connection: ssh
        ansible_user: kate
      
