all:
  hosts:
    webservers:
      192.168.0.110
      192.168.0.111
      vars:
        
    dbserver:
      192.168.0.109
      vars:
        db_name: leto
        db_user: leto
        db_pass: 1qaz@WSX
    haproxy:
      192.168.0.108
  vars:
    ansible_connection: ssh
    ansible_user: kate
      
