---

- hosts: webservers
  remote_user: kate
  become: yes

  roles:
    - web

- hosts: dbserver
  remote_user: kate
  become: yes

  roles:
    - db

- hosts: haproxy
  remote_users: kate
  become: yes

  roles:
    - haproxy

