---

- hosts: webservers
  become: yes
  roles:
    - common
    - web


- hosts: dbserver
  become: yes
  roles:
    - common
    - db

- hosts: haproxy
  become: yes
  roles:
    - common
    - haproxy

